name: CI

env:
  config: Release
  codeConnectionsSolution: CodeConnections.sln
  vsix2019proj: CodeConnections\CodeConnections.Dev16.csproj
  vsix2022proj: CodeConnections.Dev17\CodeConnections.Dev17.csproj
  vs2019testsproj: CodeConnections.Tests\CodeConnections.Tests.csproj
  vsix2019Container: ${{ github.workspace }}\CodeConnections.vsix
  vsix2022Container: ${{ github.workspace }}\CodeConnections_2022.vsix

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches:
    - main
    - 'release/**'
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Build the VSIX and upload as an artifact, and run tests
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1000 # Needed for NB.GV - https://github.com/dotnet/Nerdbank.GitVersioning/issues/423

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Add VSTest to PATH
      uses: darenm/Setup-VSTest@v1

    - name: Restore NuGet packages
      run: nuget restore ${{ env.codeConnectionsSolution }}
    
    - name: Build VS2019 VSIX
      run: |
        msbuild ${{ env.vsix2019proj }} /p:configuration=${{ env.config }} /p:TargetVsixContainer=${{ env.vsix2019Container }} /p:DeployExtension=false /verbosity:minimal
    
    - name: Build VS2022 VSIX
      run: |
        msbuild ${{ env.vsix2022proj }} /p:configuration=${{ env.config }} /p:TargetVsixContainer=${{ env.vsix2022Container }} /p:DeployExtension=false /verbosity:minimal
    
    - name: Build VS2019 unit tests
      run: |
        msbuild ${{ env.vs2019testsproj }} /p:configuration=${{ env.config }} /verbosity:minimal

    - name: Upload VS2019 VSIX Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: 'CodeConnections VSIX'
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{ env.vsix2019Container }}

    - name: Upload VS2022 VSIX Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: 'CodeConnections VSIX VS2022'
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{ env.vsix2022Container }}
    
    - name: Unit tests
      run: vstest.console.exe .\CodeConnections.Tests\bin\${{ env.config }}\CodeConnections.Tests.dll
