name: CI

env:
  config: Release
  dependsOnThatSolution: DependsOnThat.sln
  vsixContainer: ${{ github.workspace }}\DependsOnThat.vsix

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Build the VSIX and upload as an artifact, and run tests
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.1
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2

    - name: Add VSTest to PATH
      uses: darenm/Setup-VSTest@v1

    - name: Restore NuGet packages
      run: nuget restore ${{ env.dependsOnThatSolution }}
    
    - name: Build VSIX
      run: |
        msbuild ${{ env.dependsOnThatSolution }} /p:configuration=${{ env.config }} /p:TargetVsixContainer=${{ env.vsixContainer }} /p:DeployExtension=false /verbosity:minimal

    - name: Upload VSIX Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: 'DependsOnThat VSIX'
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{ env.vsixContainer }}
    
    - name: Unit tests
      run: vstest.console.exe .\DependsOnThat.Tests\bin\${{ env.config }}\DependsOnThat.Tests.dll
